"""host key + winrm verify_tls

Revision ID: 2531d17a2b88
Revises: 60df94c429f7
Create Date: 2026-07-20 06:20:48.963711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2531d17a2b88'
down_revision: Union[str, None] = '60df94c429f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default is required so the NOT NULL columns can be added to tables
    # that already have rows (SQLite rejects a NOT NULL add without a default).
    with op.batch_alter_table('ssh_hosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_key', sa.Text(), nullable=False, server_default=''))

    with op.batch_alter_table('winrm_hosts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('verify_tls', sa.Boolean(), nullable=False, server_default=sa.false())
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winrm_hosts', schema=None) as batch_op:
        batch_op.drop_column('verify_tls')

    with op.batch_alter_table('ssh_hosts', schema=None) as batch_op:
        batch_op.drop_column('host_key')

    # ### end Alembic commands ###
