"""ssh hosts table

Revision ID: 52a312bdadb3
Revises: 7fb57970bedf
Create Date: 2026-07-19 22:43:21.650959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a312bdadb3'
down_revision: Union[str, None] = '7fb57970bedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssh_hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('custom_name', sa.String(length=255), nullable=False),
    sa.Column('os_name', sa.String(length=128), nullable=False),
    sa.Column('os_id', sa.String(length=32), nullable=False),
    sa.Column('pkg_manager', sa.String(length=16), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ssh_hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ssh_hosts_host'), ['host'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssh_hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ssh_hosts_host'))

    op.drop_table('ssh_hosts')
    # ### end Alembic commands ###
