"""winrm hosts table

Revision ID: 60df94c429f7
Revises: 52a312bdadb3
Create Date: 2026-07-19 23:43:39.468261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60df94c429f7'
down_revision: Union[str, None] = '52a312bdadb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winrm_hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('use_https', sa.Boolean(), nullable=False),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('custom_name', sa.String(length=255), nullable=False),
    sa.Column('os_name', sa.String(length=128), nullable=False),
    sa.Column('os_version', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=128), nullable=False),
    sa.Column('has_winget', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('winrm_hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_winrm_hosts_host'), ['host'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winrm_hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_winrm_hosts_host'))

    op.drop_table('winrm_hosts')
    # ### end Alembic commands ###
