"""cve cache table

Revision ID: 7654c9a7ec10
Revises: ac93bb912c25
Create Date: 2026-07-19 21:48:58.295852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7654c9a7ec10'
down_revision: Union[str, None] = 'ac93bb912c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=False),
    sa.Column('total_results', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cve_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cve_cache_keyword'), ['keyword'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cve_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cve_cache_keyword'))

    op.drop_table('cve_cache')
    # ### end Alembic commands ###
