"""baseline schema

Revision ID: ac93bb912c25
Revises: 
Create Date: 2026-07-19 12:14:24.013147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac93bb912c25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('android_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=128), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('android_version', sa.String(length=32), nullable=False),
    sa.Column('sdk_version', sa.String(length=32), nullable=False),
    sa.Column('security_patch', sa.String(length=32), nullable=False),
    sa.Column('custom_name', sa.String(length=255), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('android_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_android_devices_host'), ['host'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mac', sa.String(length=32), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('custom_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_mac'), ['mac'], unique=True)

    op.create_table('software_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_version', sa.String(length=64), nullable=False),
    sa.Column('available_version', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('size_mb', sa.Float(), nullable=False),
    sa.Column('is_installed', sa.Boolean(), nullable=False),
    sa.Column('install_result', sa.Integer(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('software_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_software_packages_package_id'), ['package_id'], unique=True)

    op.create_table('windows_updates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('update_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kb_articles', sa.String(length=500), nullable=False),
    sa.Column('categories', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('size_mb', sa.Float(), nullable=False),
    sa.Column('is_downloaded', sa.Boolean(), nullable=False),
    sa.Column('requires_reboot', sa.Boolean(), nullable=False),
    sa.Column('release_date', sa.String(length=32), nullable=False),
    sa.Column('is_installed', sa.Boolean(), nullable=False),
    sa.Column('install_result', sa.Integer(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('windows_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_windows_updates_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_windows_updates_update_id'), ['update_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('windows_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_windows_updates_update_id'))
        batch_op.drop_index(batch_op.f('ix_windows_updates_kind'))

    op.drop_table('windows_updates')
    with op.batch_alter_table('software_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_software_packages_package_id'))

    op.drop_table('software_packages')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_mac'))
        batch_op.drop_index(batch_op.f('ix_devices_ip'))

    op.drop_table('devices')
    with op.batch_alter_table('android_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_android_devices_host'))

    op.drop_table('android_devices')
    # ### end Alembic commands ###
