"""agents, agent commands, replay nonces

Hand-written rather than left as autogenerated. The autogenerate pass also wanted to
drop and recreate the unique constraints created in c1d4e7f9a2b3 (the model declares
UniqueConstraint where that migration created an index — same rule, different object).
On SQLite that means rebuilding installed_software, software_packages and
windows_updates, and rebuilding inventory tables in order to add three unrelated ones
is how a migration loses data. Only the new tables are created here.

Revision ID: aca154259cc1
Revises: d2e5f8a1b4c6
Create Date: 2026-07-26 08:12:31.543022
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "aca154259cc1"
down_revision: str | None = "d2e5f8a1b4c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    present = set(sa.inspect(bind).get_table_names())

    if "agents" not in present:
        op.create_table(
            "agents",
            sa.Column("id", sa.String(length=36), nullable=False),
            sa.Column("fingerprint", sa.String(length=64), nullable=False),
            sa.Column("public_key", sa.String(length=64), nullable=False),
            sa.Column("name", sa.String(length=120), nullable=False),
            sa.Column("os_name", sa.String(length=120), nullable=False),
            sa.Column("agent_version", sa.String(length=32), nullable=False),
            sa.Column("status", sa.String(length=16), nullable=False),
            sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
            sa.Column("last_skew_seconds", sa.Float(), nullable=False),
            sa.Column("inventory_count", sa.Integer(), nullable=False),
            sa.Column("pending_updates", sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_agents_fingerprint", "agents", ["fingerprint"], unique=True)
        op.create_index("ix_agents_status", "agents", ["status"], unique=False)

    if "agent_commands" not in present:
        op.create_table(
            "agent_commands",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("agent_id", sa.String(length=36), nullable=False),
            sa.Column("kind", sa.String(length=32), nullable=False),
            sa.Column("payload", sa.Text(), nullable=False),
            sa.Column("status", sa.String(length=16), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("result", sa.Text(), nullable=False),
            sa.Column("issued_by", sa.String(length=64), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_agent_commands_agent_id", "agent_commands", ["agent_id"])
        op.create_index("ix_agent_commands_status", "agent_commands", ["status"])

    if "agent_nonces" not in present:
        op.create_table(
            "agent_nonces",
            sa.Column("nonce", sa.String(length=64), nullable=False),
            sa.Column("agent_id", sa.String(length=36), nullable=False),
            sa.Column("seen_at", sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint("nonce"),
        )
        op.create_index("ix_agent_nonces_agent_id", "agent_nonces", ["agent_id"])
        # Every signed request prunes by age, so this index must exist or the replay
        # defence turns into a full table scan on each call.
        op.create_index("ix_agent_nonces_seen_at", "agent_nonces", ["seen_at"])


def downgrade() -> None:
    for table in ("agent_nonces", "agent_commands", "agents"):
        op.drop_table(table)
