; ============================================================
;  HomeUpdater — Inno Setup installer script
;  Build with: iscc HomeUpdater.iss   (or open in the Inno Setup IDE)
;  Prerequisite: the PyInstaller bundle must exist at
;     ..\backend\dist\HomeUpdater\   (see BUILD.md)
; ============================================================

; Read the version straight from backend/VERSION so it never drifts.
#define VerFile FileOpen("..\backend\VERSION")
#define AppVersion Trim(FileRead(VerFile))
#expr FileClose(VerFile)

#define AppName "HomeUpdater"
#define AppNameAr "محدِّث المنزل"
#define AppPublisher "HomeUpdater"
#define AppExe "HomeUpdater.exe"

[Setup]
; A stable, unique AppId — do NOT change between releases (keeps upgrades clean).
AppId={{8F3A1C7E-2B4D-4E6A-9C1F-5D7E8A9B0C1D}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
; The backend drives Windows Update / winget / nmap — it needs elevation.
PrivilegesRequired=admin
; We close the running app ourselves (a custom page below): the built-in Restart
; Manager closes HomeUpdater.exe but not its msedgewebview2.exe child processes,
; which keep the _internal DLLs locked -> "unable to close all applications".
CloseApplications=no
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
OutputDir=Output
OutputBaseFilename=HomeUpdater-Setup-{#AppVersion}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
; Branding (generated by 03_الموارد\logo\generate_icons.py + generate_wizard_banners.py).
SetupIconFile=assets\HomeUpdater.ico
UninstallDisplayIcon={app}\{#AppExe}
; Wizard banners: 100% + 200% variants, Inno picks by DPI.
WizardImageFile=assets\wizard-large.bmp,assets\wizard-large@2x.bmp
WizardSmallImageFile=assets\wizard-small.bmp,assets\wizard-small@2x.bmp

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
; Arabic needs a third-party Languages\Arabic.isl (not shipped with Inno). Add it,
; then enable: Name: "arabic"; MessagesFile: "Languages\Arabic.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
; Auto-start via a Scheduled Task with 'Run with highest privileges' — the app
; needs elevation, and a plain Startup-folder shortcut can't elevate (it would
; UAC-prompt or fail every logon). A logon task runs it elevated with NO prompt.
Name: "startuptask"; Description: "تشغيل {#AppName} تلقائياً عند تسجيل الدخول / Start at sign-in"; GroupDescription: "Startup:"; Flags: unchecked

; NO [InstallDelete] FOR frontend_dist\assets — deliberately.
; v1.10.3 pruned the stale Vite bundles with [InstallDelete], which Inno runs BEFORE
; [Files]. Measured consequence on a real machine (v1.10.4 upgrade): a locked file
; aborted the copy, and because Inno's rollback does NOT restore [InstallDelete]
; deletions, the machine was left with an installed app whose UI folder was gone.
; The prune now happens in CurStepChanged(ssPostInstall) — after the new build is
; safely in place — so a failed install is a no-op instead of destructive.

[Files]
; The entire PyInstaller onedir output.
Source: "..\backend\dist\{#AppName}\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion
; Network discovery works WITHOUT nmap/Npcap (pure-Python TCP+ARP scanner,
; settings.scan_method="auto"). Nmap is only an optional enhancement: if the
; user installs it separately it is used automatically. We do NOT bundle
; Npcap (its free license restricts redistribution).

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExe}"
Name: "{group}\Uninstall {#AppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExe}"; Tasks: desktopicon

[Run]
; Create the elevated logon Scheduled Task (only pass the exe path — no args — so
; single-level quoting handles the space in "Program Files"). /RL HIGHEST = run
; elevated without a UAC prompt at logon.
Filename: "{sys}\schtasks.exe"; Parameters: "/Create /TN ""HomeUpdater"" /TR ""{app}\{#AppExe}"" /SC ONLOGON /RL HIGHEST /F"; Flags: runhidden; Tasks: startuptask
Filename: "{app}\{#AppExe}"; Description: "{cm:LaunchProgram,{#AppName}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; Remove the logon Scheduled Task (ignore the error if it was never created).
Filename: "{sys}\schtasks.exe"; Parameters: "/Delete /TN ""HomeUpdater"" /F"; Flags: runhidden; RunOnceId: "DelHomeUpdaterTask"
; Stop the running instance (and its WebView2 children, via /T) before removing files.
Filename: "{sys}\taskkill.exe"; Parameters: "/F /T /IM {#AppExe}"; Flags: runhidden; RunOnceId: "StopHomeUpdater"
; Same lock, mirror image: the detached adb server and any orphaned WebView2 host keep
; files in {app} open, so a silent uninstall would leave the folder behind. Kill only
; the ones running FROM the install folder — never the user's own adb.
Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -Command ""Get-Process adb,msedgewebview2 -ErrorAction SilentlyContinue | Where-Object {{ $_.Path -and $_.Path.StartsWith('{app}', 'OrdinalIgnoreCase') } | Stop-Process -Force"""; Flags: runhidden; RunOnceId: "StopHomeUpdaterHelpers"

; NOTE: user data in %APPDATA%\HomeUpdater (DB, config, logs) is intentionally
; left in place on uninstall. A future "remove my data?" prompt can clear it.

[Code]
{ ---- Close the running HomeUpdater (incl. its msedgewebview2 children) before update ---- }
var
  ClosePage: TWizardPage;
  CloseCheck: TNewCheckBox;
  AppMemo: TNewMemo;

function AppIsRunning(): Boolean;
var
  RC: Integer;
begin
  { `find` exits 0 only when HomeUpdater.exe appears in the tasklist output }
  Result := Exec(ExpandConstant('{cmd}'),
    '/C tasklist /FI "IMAGENAME eq {#AppExe}" | find /I "{#AppExe}"',
    '', SW_HIDE, ewWaitUntilTerminated, RC) and (RC = 0);
end;

function AdbPath(): String;
begin
  Result := ExpandConstant('{app}\_internal\platform-tools\adb.exe');
end;

function FileIsReplaceable(const FileName: String): Boolean;
var
  RC: Integer;
begin
  { Opening with FileShare.None succeeds only if nothing else holds the file — the
    same question Inno's DeleteFile is about to ask, asked while we can still stop
    cleanly instead of half-way through the copy. }
  Result := True;
  if not FileExists(FileName) then
    Exit;
  if Exec(ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'),
          '-NoProfile -ExecutionPolicy Bypass -Command "try { $f=[IO.File]::Open('''
          + FileName + ''',''Open'',''ReadWrite'',''None''); $f.Close(); exit 0 }'
          + ' catch { exit 1 }"',
          '', SW_HIDE, ewWaitUntilTerminated, RC) then
    Result := (RC = 0);
end;

procedure StopAdbServer();
var
  RC: Integer;
begin
  { MEASURED (v1.10.4 upgrade, 2026-07-25): adb starts a SERVER process that
    detaches itself, so it outlives HomeUpdater.exe and 'taskkill /T' on the app
    does not touch it. It then holds _internal\platform-tools\adb.exe open, Inno
    cannot replace the file, and a silent install (where the Abort/Retry/Ignore box
    defaults to Abort) aborts and rolls back — which deleted frontend_dist\assets
    and left an installed app with no UI at all.
    Deliberately NOT 'taskkill /IM adb.exe' and NOT 'adb kill-server': both would
    also kill an adb the user runs for their own Android work. This kills only
    processes whose image lives inside OUR install folder.
    msedgewebview2 is here too: the app's WebView2 hosts sometimes outlive it and
    keep _internal DLLs mapped — the same class of lock, different process.
    StartsWith (not -like) because a custom install path containing [ or ] would
    make -like treat it as a wildcard pattern and match nothing. }
  Exec(ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'),
       '-NoProfile -ExecutionPolicy Bypass -Command "Get-Process adb,msedgewebview2'
       + ' -ErrorAction SilentlyContinue | Where-Object { $_.Path -and'
       + ' $_.Path.StartsWith(''' + ExpandConstant('{app}') + ''', ''OrdinalIgnoreCase'')'
       + ' } | Stop-Process -Force"',
       '', SW_HIDE, ewWaitUntilTerminated, RC);
end;

procedure PruneStaleBundles();
var
  Dir, AssetsDir: String;
  Blob, Content: AnsiString;
  FR: TFindRec;
  Names, Seen: TStringList;
  I, Pass: Integer;
  Grew: Boolean;
begin
  { Vite fingerprints bundle names, so every upgrade adds files and never removes the
    old ones (12 dead files / 3.6 MB had piled up by v1.10.2). This USED to be an
    InstallDelete entry — but that runs before the copy and is not rolled back, so
    any later failure left the app with no UI. Doing it here, after ssPostInstall,
    means a failed install leaves the previous bundles exactly where they were.
    A file is kept if its name appears in index.html or inside any kept .js: the
    entry bundle references lazily-loaded chunks (the ~6 MB PDF chunk among them),
    so scanning index.html alone would delete a live file.
    Fails CLOSED: if index.html cannot be read, nothing is deleted. }
  Dir := ExpandConstant('{app}\_internal\frontend_dist');
  AssetsDir := Dir + '\assets';
  if not LoadStringFromFile(Dir + '\index.html', Blob) then
  begin
    Log('PruneStaleBundles: index.html unreadable — pruning skipped');
    Exit;
  end;
  Names := TStringList.Create();
  Seen := TStringList.Create();
  try
    if FindFirst(AssetsDir + '\*', FR) then
    begin
      try
        repeat
          if (FR.Attributes and FILE_ATTRIBUTE_DIRECTORY) = 0 then
            Names.Add(FR.Name);
        until not FindNext(FR);
      finally
        FindClose(FR);
      end;
    end;
    for Pass := 1 to 3 do
    begin
      Grew := False;
      for I := 0 to Names.Count - 1 do
      begin
        if Seen.IndexOf(Names[I]) >= 0 then
          Continue;
        if Pos(Names[I], Blob) = 0 then
          Continue;
        Seen.Add(Names[I]);
        if LowerCase(ExtractFileExt(Names[I])) = '.js' then
        begin
          if LoadStringFromFile(AssetsDir + '\' + Names[I], Content) then
          begin
            Blob := Blob + Content;
            Grew := True;
          end;
        end;
      end;
      if not Grew then
        Break;
    end;
    for I := 0 to Names.Count - 1 do
    begin
      if Pos(Names[I], Blob) = 0 then
      begin
        Log('Pruning stale bundle: ' + Names[I]);
        DeleteFile(AssetsDir + '\' + Names[I]);
      end;
    end;
  finally
    Names.Free();
    Seen.Free();
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    PruneStaleBundles();
end;

procedure KillAppTree();
var
  RC: Integer;
  I: Integer;
begin
  { /T kills the process tree so the msedgewebview2 children die too and release
    the locked _internal DLLs. Then wait until the handles are actually gone. }
  Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /T /IM {#AppExe}', '',
       SW_HIDE, ewWaitUntilTerminated, RC);
  for I := 1 to 12 do
  begin
    if not AppIsRunning() then Break;
    Sleep(500);
  end;
  StopAdbServer();
end;

procedure InitializeWizard();
var
  Lbl: TNewStaticText;
begin
  ClosePage := CreateCustomPage(wpReady,
    'إغلاق التطبيقات قيد التشغيل / Close running applications',
    'HomeUpdater يعمل حالياً ويستخدم ملفات يجب تحديثها.');

  Lbl := TNewStaticText.Create(ClosePage);
  Lbl.Parent := ClosePage.Surface;
  Lbl.Top := 0;
  Lbl.Width := ClosePage.SurfaceWidth;
  Lbl.Caption := 'التطبيقات التي يجب إغلاقها قبل المتابعة:';

  AppMemo := TNewMemo.Create(ClosePage);
  AppMemo.Parent := ClosePage.Surface;
  AppMemo.Left := 0;
  AppMemo.Top := ScaleY(20);
  AppMemo.Width := ClosePage.SurfaceWidth;
  AppMemo.Height := ScaleY(70);
  AppMemo.ReadOnly := True;
  AppMemo.ScrollBars := ssVertical;
  AppMemo.Lines.Add('• HomeUpdater.exe');
  AppMemo.Lines.Add('• msedgewebview2.exe (نوافذ التطبيق التابعة)');

  CloseCheck := TNewCheckBox.Create(ClosePage);
  CloseCheck.Parent := ClosePage.Surface;
  CloseCheck.Left := 0;
  CloseCheck.Top := ScaleY(100);
  CloseCheck.Width := ClosePage.SurfaceWidth;
  CloseCheck.Height := ScaleY(24);
  CloseCheck.Caption := 'أغلق HomeUpdater تلقائياً ثم تابع التحديث (مُوصى به)';
  CloseCheck.Checked := True;
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  { Only show the close page when the app is actually running. }
  Result := (PageID = ClosePage.ID) and (not AppIsRunning());
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID = ClosePage.ID then
  begin
    if AppIsRunning() then
    begin
      if CloseCheck.Checked then
      begin
        KillAppTree();
        if AppIsRunning() then
        begin
          MsgBox('تعذّر إغلاق HomeUpdater تلقائياً. أغلقه يدوياً ثم اضغط «التالي».',
                 mbError, MB_OK);
          Result := False;
        end;
      end
      else
      begin
        if MsgBox('HomeUpdater ما زال يعمل؛ قد يفشل التحديث بدون إغلاقه. المتابعة؟',
                  mbConfirmation, MB_YESNO) = IDNO then
          Result := False;
      end;
    end;
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  { Backstop right before files are copied — guarantees the tree is down even if
    the app was launched between the page and the copy. Runs in silent mode too,
    which the wizard page does not.
    The adb server is stopped UNCONDITIONALLY here: it outlives the app, so it can
    be holding platform-tools\adb.exe even when AppIsRunning() is already false —
    that is exactly how the v1.10.4 upgrade aborted. }
  Result := '';
  StopAdbServer();
  if AppIsRunning() then
    KillAppTree();
  if AppIsRunning() then
  begin
    Result := 'HomeUpdater ما زال قيد التشغيل ولا يمكن تحديث ملفاته. أغلقه ثم أعد المحاولة.';
    Exit;
  end;
  { Last gate before Inno starts touching files: if something we could not stop is
    still holding adb.exe, fail HERE. Returning a message aborts the install before
    a single file is replaced, which is a no-op; letting it run would fail mid-copy
    instead — and in a non-interactive install (Intune/GPO run in session 0, where
    the Abort/Retry/Ignore box is invisible) that means hanging until the deployment
    tool kills setup. }
  if not FileIsReplaceable(AdbPath()) then
    Result := 'الملف _internal\platform-tools\adb.exe قيد الاستخدام من عملية أخرى،'
      + ' فتعذّر التحديث قبل أن يبدأ (لم يُغيَّر أي ملف). أغلق أي أداة adb ثم أعد المحاولة.'
      + #13#10 + 'adb.exe is locked by another process; the upgrade stopped before'
      + ' changing anything. Close any adb tool and retry.';
end;
